- name: check email when cert-manager
  assert:
    that:
      - cert_manager_email | default(false)

- name: check acme ca defined in local
  assert:
    that:
      - kubeapps_internal_acme_external_ip | default(false)
      - kubeapps_internal_acme_host | default(false)
  when: cert_manager_is_internal
