---
- name: Get Ingress service infos
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: traefik
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: yes
    namespace: kube-system
  register: ingress_infos

- name: check ingress service infos available
  assert:
    that:
      - ingress_infos.resources | length > 0

- name: Recover base64 encoded ca content to trust
  slurp:
    src: "{{ kubeapps_internal_acme_ca_file }}"
  register: ca_file_content

- set_fact:
    kubeapps_internal_acme_ca_content: "{{ ca_file_content.content | b64decode }}"
    kubeapps_ingress_controller_ip: "{{ ingress_infos.resources[0].spec.clusterIP }}"
