---

# - import_tasks: kube-system.yml
#   tags: [kubeapps]

- import_tasks: checks.yml
  tags: [kubeapps]

- import_tasks: local-dns-ingress.yml
  when: cert_manager_is_local
  tags: [kubeapps]

- import_tasks: manifests.yml
  tags: [kubeapps]
