---
# Kubeapps internal acme server
kubeapps_internal_acme_external_ip: ~
kubeapps_internal_acme_host: acme-internal.k3s.local
kubeapps_internal_acme_ca_file: ~

# HelmChart Custom Resource Definition for cert manager
# see https://cert-manager.io/docs/configuration/acme/
cert_manager_namespace: cert-manager
cert_manager_acme_url: "{{ letsencrypt_prod }}"
cert_manager_email: ""
cert_manager_private_key_secret: test_secret
cert_manager_is_internal: "{{ kubeapps_internal_acme_ca_file is not none }}"

# HelmChart Custom Resource Definition for dex oidc connector
dex_namespace: dex
dex_hostname: dex.k3s.local
dex_client_id: kubeapps
dex_client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
dex_github_client_id: ~
dex_github_client_secret: ~
dex_github_client_org: ~
dex_github_client_team: ~

# HelmChart Custom Resource Definition for kubeapps variables
kubeapps_namespace: kubeapps
kubeapps_user: "{{ ansible_user | default('root') }}"
kubeapps_hostname: kubeapps.k3s.local
# default to result of echo "not-good-secret" | base64
kubeapps_oauth_proxy_cookie_secret: bm90LWdvb2Qtc2VjcmV0Cg==
