---
# Kubeapps
# Cluster core variables
kubeapps_k8s_ingress_class: traefik

# HelmChart Custom Resource Definition for cert manager
# see https://cert-manager.io/docs/configuration/acme/
cert_manager_namespace: cert-manager

cert_manager_email: ""
cert_manager_private_key_secret: test_secret

# Default to local acme issuer
cert_manager_cluster_issuer: letsencrypt-local
# HelmChart Custom Resource Definition for dex oidc connector
cert_manager_is_local: "{{ cert_manager_cluster_issuer == 'letsencrypt-local' }}"

kubeapps_dex_namespace: dex
kubeapps_dex_hostname: dex.k3s.local
kubeapps_dex_client_id: kubeapps
kubeapps_dex_client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0

kubeapps_dex_github_client_id: ~
kubeapps_dex_github_client_secret: ~
kubeapps_dex_github_client_org: ~
kubeapps_dex_github_client_team: ~

# HelmChart Custom Resource Definition for kubeapps variables
kubeapps_namespace: kubeapps
kubeapps_user: "{{ ansible_user | default('root') }}"
kubeapps_hostname: kubeapps.k3s.local

kubeapps_authProxy: {}
kubeapps_authProxy_default:
  scope: email openid profile
  enabled: true
  provider: oidc
  clientID: "{{ kubeapps_dex_client_id }}"
  clientSecret: "{{ kubeapps_dex_client_secret }}"
  # default to result of echo "not-good-secret" | base64
  cookieSecret: 'bm90LWdvb2Qtc2VjcmV0Cg=='
  extraFlags:
    - --oidc-issuer-url=https://{{ kubeapps_dex_hostname }}
    - --redirect-url=https://{{ kubeapps_hostname }}/oauth2/callback
    - --reverse-proxy=true

# Merge user config with defaults
kubeapps_authProxy_final: "{{ kubeapps_authProxy_default | combine(kubeapps_authProxy) }}"
