---
# Kubeapps
# Cluster core variables
kubeapps_k8s_ingress_class: traefik

# Certificate authority for local trusted SSL
kubeapps_ca_ssl_dir: "{{ ansible_user_dir }}/.ssl"
kubeapps_ca_root_key_passphrase: kubeapps
kubeapps_ca_root_location_pem: "{{ kubeapps_ca_ssl_dir }}/ca-k3s.pem"
kubeapps_ca_root_location_crt: "{{ kubeapps_ca_ssl_dir }}/ca-k3s.crt"

# HelmChart Custom Resource Definition for cert manager
# see https://cert-manager.io/docs/configuration/acme/
cert_manager_namespace: cert-manager

cert_manager_email: ""
cert_manager_chart_crd: cert-manager-chart-crd.yml
cert_manager_private_key_secret: test_secret
# default to self signed
cert_manager_cluster_issuer: selfsigned-ca-issuer

# # HelmChart Custom Resource Definition for dex oidc connector
kubeapps_dex_chart_crd: dex-chart-crd.yml

kubeapps_dex_namespace: dex
kubeapps_dex_issuer: 127.0.0.1:5556
kubeapps_dex_client_id: example-app
kubeapps_dex_client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0

kubeapps_dex_github_client_id: ""
kubeapps_dex_github_client_secret: ""
kubeapps_dex_github_client_org: ""
kubeapps_dex_github_client_team: ""

# HelmChart Custom Resource Definition for kubeapps variables
kubeapps_namespace: kubeapps
kubeapps_chart_crd: kubeapps-chart-crd.yml
kubeapps_user: "{{ ansible_user | default('root') }}"
kubeapps_hostname: kubeapps.svc.local

kubeapps_authProxy: {}
kubeapps_authProxy_default:
  scope: email
  enabled: true
  provider: oidc  
  clientID: "example-app"
  clientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0"
  # default to result of echo "not-good-secret" | base64
  cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
# Merge user config with defaults
kubeapps_authProxy_final: "{{ kubeapps_authProxy_default | combine(kubeapps_authProxy) }}"
