---
- name: Converge
  hosts: all
  become: true
  vars:
    molecule_is_test: true
    k3s_state: started
    k3s_become: true

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  pre_tasks:
    - name: Ensure test dependencies are installed (Debian).
      package: 
        name: iptables
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
