---
- name: Converge
  hosts: all
  become: true
  vars:
    molecule_is_test: true
    k3s_build_cluster: false
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Ensure test dependencies are installed (Debian).
      package: 
        name: [iproute2,gpg-agent]
        state: present
      when: ansible_os_family == 'Debian'

    - name: Gather facts.
      action: setup
