---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k3s-node-0
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: k3snet

provisioner:
  name: ansible
verifier:
  name: ansible
