---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get single node
      command: kubectl get nodes
      changed_when: false
      register: kubernetes_nodes

    - name: Print list of running nodes.
      debug: var=kubernetes_nodes.stdout

    - name: Assert master node ready
      ansible.builtin.assert:
        that: '"node-0   Ready    control-plane,master" in kubernetes_nodes.stdout'

    - name: Wait for pods to start fully
      ansible.builtin.pause:
        minutes: 2

    - name: Get all running pods.
      command: kubectl get pods -n kube-system
      changed_when: false
      register: kube_system_pods

    - name: Tranform pods stdout to list
      ansible.builtin.set_fact:
        pods: "{{ kube_system_pods.stdout.split('\n') | list | 
          reject('search', 'NAMESPACE') }}"

    - name: Print list of pods.
      debug: var=pods

    - name: Get running pods
      ansible.builtin.set_fact:
        running: "{{ pods | select('search', 'Running') | list }}"

    - name: Set assertions list
      ansible.builtin.set_fact:
        pod_assertions:
          - "{{ (running | select('search', '1/1') | list) | length >= 3 }}"
          - "{{ (running | select('search', '2/2') | list) | length == 1 }}"
          - "{{ (pods | select('search', 'Completed') | list) | length >= 3 }}"

    - name: Assert required pods up
      ansible.builtin.assert:
        that: "{{ pod_assertions | list }}"
        fail_msg: "{{ pod_assertions | join(' - ') }}"

    - name: Assert kube-system helm task for kubeapps is ok
      ansible.builtin.assert:
        that: "{{ (pods | 
          select('search', 'helm-install-kubeapps') | 
          select('search', 'Completed') | list
          ) | length }}"

    - name: Get all kubeapps running pods.
      command: kubectl get pods -n kubeapps
      changed_when: false
      register: kubeapps_pods

    - name: Get kubeapps pods
      ansible.builtin.set_fact:
        kubeapps_running: "{{ kubeapps_pods.stdout.split('\n') | 
          reject('search', 'NAMESPACE') | 
          select('search', 'Running') | list }}"

    - name: Print list of kubeapps pods.
      debug: var=kubeapps_running

    - name: Assert kubeapps all pods running
      ansible.builtin.assert:
        that: "{{ (kubeapps_running | list) | length >= 9 }}"
